### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef#840]
- [x] Finalize current PRs (review + tests)
   - hugsy/gef#842 
   - hugsy/gef#839 
 - [x] Renamed `master` -> `main` here & extras
   - hugsy/gef-extras#65   
   - hugsy/gef#845
 - [x] Make sure docs is updated
   - [ca67ced](https://github.com/hugsy/gef/commit/ca67ced46b2c9139513a4399da5916240170a883)
 - [x] GithubActions: replace `gaurav-nelson/github-action-markdown-link-check` actions with `lycheeverse/lychee-action`
   - hugsy/gef#841
 - [x] move `ropper`, `set-permission` and `cs-disassemble` to `gef-extras`
   - hugsy/gef#841

**Comment by hugsy** [comment]
Moving #838 to next milestone, there's still plenty of smaller bugs before `qemu` and `remote` are fully functional.
